### ISSUE TITLE
Issues in generating snapshot of HTTPS pages

### ISSUE THREAD

**Issue by raeesaa** [kimmobrunfeldt/url-to-image#1]
Hi,

First, I would like to thank you for a great library. I have been using this library in production since last three months and it has been a great help since the page I need to take snapshot of loads AJAX data. But I recently started facing issues after the URL I take snapshot of was changed to HTTPS. The snapshot no longer gets generated and I end up landing in 'fail()' callback.

The only logs that are returned by library are: 

```
[Error]
```

And therefore I am not being able to do anything much about it.

I know there are issues in loading HTTPS urls with phantom.js but there are workarounds for getting it to work. It would be great if you help me in fixing it.

Thanks,
Raeesaa

**Comment by kimmobrunfeldt** [comment]
I'll take a look

**Comment by kimmobrunfeldt** [comment]
Fix for this is released in 0.2.0.

**Comment by kimmobrunfeldt** [comment]
This functionality has been changed in 1.0.0. See [CHANGELOG.md](https://github.com/kimmobrunfeldt/url-to-image/blob/master/CHANGELOG.md) to see API changes.
