### ISSUE TITLE
Mak it possible to use phantomjs options

### ISSUE THREAD

**Issue by gimler** [kimmobrunfeldt/url-to-image#5]
IT would be great when all phantomjs options would be available.

Simple forward all additional options as args to phantomjs.

So that it is possible to set proxy or activate debug mode for example.

**Comment by kimmobrunfeldt** [comment]
That's a good idea. I'm currently quite full of work but I'll try to look into this in the near future

**Comment by kimmobrunfeldt** [comment]
This is now possible with the new option `phantomArguments`. It has been released in 1.0.0 version.
