### ISSUE TITLE
invoking url-to-image functionality from browser script

### ISSUE THREAD

**Issue by Priyalc** [kimmobrunfeldt/url-to-image#6]
Hi,

I have installed node.js, phantomjs on my server. This utility works perfectly well when it fired through the phantomjs. But my requirement is I want to call this functionality from browser script on click of button. how can I call this one through browser script?

**Comment by kimmobrunfeldt** [comment]
This library depends on phantomjs. If you want to call this through a browser, you should have a server running phantomjs behind the scenes. That functionality is out of this library's scope.

If you end up creating such service, it'd be nice if you could share it here. I can add a link to readme.
