### ISSUE TITLE
Support for taking a thumbnail screenshot

### ISSUE THREAD

**Issue by nmsbane** [kimmobrunfeldt/url-to-image#8]
Hi, I would like to have a feature to not only take screenshots of entire page, i just want some portion of the page, as a screeenshot.  

i.e instead of
![miguel](https://cloud.githubusercontent.com/assets/8592959/11612834/8dc493e4-9c2f-11e5-8a36-801b637efcb1.jpg) this kind of image, i would like to have a this image

https://s3-us-west-2.amazonaws.com/banesbookmarks/bookmark-532c8eeb-be62-443a-867b-5ea67ab72552.jpg

**Comment by Magiweb** [comment]
I second this request. URL-to-image makes taking a snapshot of a website dead simple, but we definitely need to be able to do basic things like cropping.

Is it possible in some way to pass these arguments to PhantomJS?

**Comment by kimmobrunfeldt** [comment]
If phantomjs supports cropping as cli arguments, you can use `options.phantomArguments`. If not, I'm happy to merge a pull request which would implement this feature.

**Comment by nmsbane** [comment]
For getting the cropped image, i inserted the following line in the renderPage function in url-to-image.js file 

`page.clipRect = { width: 1200, height: 800 };`

I can able to achieve a cropped image, but not sure whether this code change is good or bad

**Comment by Magiweb** [comment]
kimmobrunfeldt I was unable to find an option to pass the cropping instruction as a cli argument to PhantomJS. Do you know how to do this?

**Comment by kimmobrunfeldt** [comment]
It seemed that phantomjs doesn't provide this as a commandline argument, that should be implemented with page.clipRect as @nmsbane commented

**Comment by Magiweb** [comment]
I've extended your library to include support for this, and also allows you to choose file type and quality. I'll clone and send merge request to you now

**Comment by Magiweb** [comment]
@kimmobrunfeldt I can't seem to create a new branch and push. Gives me a 403 error - seems you'll need to make me a collaborator, or I can attach the 2 files I changed here if you want? 

Let me know.

**Comment by kimmobrunfeldt** [comment]
@Magiweb ok sounds good. Please follow these instructions to create a pull request to this repository https://help.github.com/articles/creating-a-pull-request/

**Comment by Magiweb** [comment]
@kimmobrunfeldt I can't. Point is I can't push to your Github repo, not even in a new branch, so I can't create a pull request. I tried creating a new branch and pushing, and I also tried pushing to the master branch - result is the same: remote: Permission to kimmobrunfeldt/url-to-image.git denied to Magiweb.

Unless I'm missing something, I think you need to add me as a collaborator, or alternatively I can attach the files here?

**Comment by kimmobrunfeldt** [comment]
You first need to fork this repository to your own account and add changes there. See this article: https://help.github.com/articles/using-pull-requests/

**Comment by Magiweb** [comment]
Learned something new about Github :) 
I forked, pushed and created a pull request.

**Comment by Magiweb** [comment]
@kimmobrunfeldt are you going to merge my changes? I'd like this to be updated in the npm package so that future updates don't override the changes I made...

**Comment by kimmobrunfeldt** [comment]
Cool :) @Magiweb I'll try to merge them as soon as possible.

**Comment by nmsbane** [comment]
thanks @Magiweb  and @kimmobrunfeldt
